version: '3'
services:
  whoami:
    image: containous/whoami:v1.3.0
    networks:
     - traefik_outside-world
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.whoami-redirect-websecure.redirectscheme.scheme=https
        - traefik.http.routers.whoami-web.middlewares=whoami-redirect-websecure
        - traefik.http.routers.whoami-web.rule=Host(`whoami.example.com`)
        - traefik.http.routers.whoami-web.entrypoints=web
        - traefik.http.routers.whoami-websecure.rule=Host(`whoami.example.com`)
#        - traefik.http.routers.whoami-websecure.tls.certresolver=mytlschallenge
        - traefik.http.routers.whoami-websecure.tls=true
        - traefik.http.routers.whoami-websecure.entrypoints=websecure
        - traefik.http.services.whoami-websecure.loadbalancer.server.port=80
#      mode: global
      replicas: 5

networks:
  traefik_outside-world:
    external: true
  traefik_internal-network:
    external: true
  default:
    external:
      name: traefik_internal-network
